# Generated by Django 4.2.7 on 2023-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_user_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='librarydb',
            name='not_more_books_issued',
        ),
        migrations.AddConstraint(
            model_name='librarydb',
            constraint=models.CheckConstraint(check=models.Q(('total_count__gte', models.F('issued_count')), ('issued_count__gte', 0)), name='not_more_books_issued', violation_error_message='ERROR: Either trying to return a book which was not issued, or trying to issue more books that available!'),
        ),
    ]
