# Generated by Django 4.2.7 on 2023-11-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_booksandusers_t_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksandusers",
            name="t_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.transactions",
            ),
        ),
    ]
